[package]
name = "usps_v3_api"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
authors = ["César A Vergara Buenaventura <cesarvergarab@gmail.com>"]
description = "Cliente asíncrono e idiomático para la API REST v3 de USPS (United States Postal Service) en Rust."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/cesarvergarab/usps_v3_api"
homepage = "https://github.com/cesarvergarab/usps_v3_api"
documentation = "https://docs.rs/usps_v3_api"
keywords = ["usps", "postal", "shipping", "tracking", "api"]
categories = ["api-bindings", "asynchronous", "web-programming::http-client"]

[dependencies]
